name: Continuous Integration ðŸ› ï¸

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 1.6.1

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ðŸ“¦
        uses: actions/checkout@v4

      - name: Set up Python ðŸ
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Poetry ðŸ’¼
        run: pip install poetry==${{ env.POETRY_VERSION }}

      - name: Cache Dependencies ðŸ—„ï¸
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
            ${{ runner.os }}-

      - name: Install Dependencies ðŸ’¾
        run: poetry install

      - name: ðŸŽ¨ Run Black Code Formatter
        run: poetry run black --check --diff .

      - name: ðŸ“– Run Flake8 Linter
        run: poetry run flake8 src tests

      - name: ðŸ“Ÿ Run MyPy Type Checker
        run: poetry run mypy src tests

      - name: ðŸ§¹ Run isort
        run: poetry run isort --check-only --diff .

      - name: ðŸ” Run Pylint Code Analyzer
        run: poetry run pylint src tests

  #      - name: ðŸ§ª Run Pytest
  #        run: poetry run pytest --cov=app

  #      - name: ðŸ“Š Generate Coverage Report
  #        run: poetry run coverage xml

  build:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ðŸ“¦
        uses: actions/checkout@v4

      - name: Set up Python ðŸ
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Poetry ðŸ’¼
        run: pip install poetry==${{ env.POETRY_VERSION }}

      - name: Build Lambda Function ðŸ—ï¸
        run: |
          mkdir -p dist/function
          cp -r src/* dist/function/
          cd dist/function
          zip -r ../function.zip .
          cd ..
          rm -rf ./function

      - name: Build Lambda Layer ðŸ§©
        run: |
          mkdir -p dist/layer/python
          poetry export -f requirements.txt --output requirements.txt --without-hashes --without dev
          pip install -r requirements.txt --no-deps -t dist/layer/python
          cd dist/layer
          zip -r ../layer.zip .
          cd ..
          rm -rf ./layer

      - name: Upload Built Artifacts ðŸ“¤
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    env:
      LAMBDA_NAME: dev-datapoints-uploader
      LAYER_NAME: dev-datapoints-uploader-layer

    steps:
      - name: Download Built Artifacts ðŸ“¥
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Configure AWS Credentials ðŸ”
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::071941506442:role/githubActionCodeDeploy
          aws-region: us-east-1

      - name: Deploy to AWS Lambda ðŸš€
        run: aws lambda update-function-code --function-name ${{ env.LAMBDA_NAME }} --zip-file fileb://dist/function.zip

      - name: Publish a new version of the Lambda Layer ðŸŽ›ï¸
        run: |
          LAYER_VERSION=$(aws lambda publish-layer-version \
          --layer-name ${{ env.LAYER_NAME }} \
          --zip-file fileb://dist/layer.zip \
          --compatible-runtimes python${{ env.PYTHON_VERSION }} \
          --compatible-architectures x86_64 \
          --query Version \
          --output text)
          echo "LAYER_VERSION=$LAYER_VERSION" >> $GITHUB_ENV

      - name: Update Lambda Configuration to use New Layer Version ðŸ”—
        run: |
          aws lambda update-function-configuration \
          --function-name ${{ env.LAMBDA_NAME }} \
          --layers arn:aws:lambda:us-east-1:071941506442:layer:${{ env.LAYER_NAME }}:$LAYER_VERSION
          aws lambda wait function-updated \
          --function-name ${{ env.LAMBDA_NAME }}

      - name: Delete Previous Lambda Layer Version ðŸ—‘ï¸
        if: env.LAYER_VERSION > 1
        run: |
          PREVIOUS_LAYER_VERSION=$((LAYER_VERSION - 1))

          # Delete the previous layer version
          aws lambda delete-layer-version \
          --layer-name ${{ env.LAYER_NAME }} \
          --version-number $PREVIOUS_LAYER_VERSION
